name: docs

on:
  push:
    branches:
      - main
  pull_request:

env:
  UV_FROZEN: "1"

jobs:
  build_sphinx_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          # Need to clone everything to embed the version.
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest-known"
          enable-cache: true
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv sync

      - name: Build documentation
        working-directory: ./doc
        run: uv run package-docs build -n -W
